repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: \.txt$
      - id: trailing-whitespace  # Remove trailing whitespaces
      - id: check-merge-conflict

  # Fix common spelling mistakes
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args: [
          '--ignore-words-list', 'vraster',
          '--ignore-regex', '\bhist\b',
          '--'
        ]
        types_or: [python, rst, markdown]
        files: ^(src|doc|tests)/

  # Replace relative imports (e.g. 'from . import georaster' -> 'from geoutils import georaster')
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  # Format the code aggressively using black
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [--line-length=120]

  # Lint the code using flake8
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        # More than one argument in the second list, so need to pass arguments as below (and -- to finish)
        args: [
                '--max-line-length', '120',  # we can write dicts however we want
                '--extend-ignore', 'E203,C408', # flake8 disagrees with black, so this should be ignored.
                '--'
        ]
        additional_dependencies:
                - flake8-comprehensions==3.12.0
                - flake8-bugbear==23.3.23
        files: ^(src|tests)

  # Lint the code using mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        args: [
              #--config-file=mypy.ini,
              --strict,
              --implicit-optional,
              --ignore-missing-imports,  # Don't warn about stubs since pre-commit runs in a limited env
              --allow-untyped-calls,  # Dynamic function/method calls are okay. Untyped function definitions are not okay.
              --show-error-codes,
              --no-warn-unused-ignores,  # Ignore 'type: ignore' comments that are not used.
              --disable-error-code=attr-defined,  # "Module has no attribute 'XXX'" occurs because of the pre-commit env.
              --disable-error-code=name-defined,  # "Name 'XXX' is not defined" occurs because of the pre-commit env.
              --disable-error-code=var-annotated,
              --disable-error-code=no-any-return

        ]
        additional_dependencies: [tokenize-rt==5.0.0, numpy==1.24.2]
        files: ^(src|tests|doc/code)

  # Sort the contents of modules based on how they co-depend
  - repo: https://github.com/bwhmather/ssort
    rev: v0.11.6
    hooks:
      - id: ssort

  # Sort imports using isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
            - id: isort
              args: ["--profile", "black"]

  # Automatically upgrade syntax to a minimum version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
          - id: pyupgrade
            args: [--py38-plus]

  # Various formattings
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
          # Single backticks should apparently not be used
          - id: rst-backticks
          # Check that all directives end with double colon
          - id: rst-directive-colons
            types: [text]
            types_or: [python, rst]
          # Inline code should not touch normal text
          - id: rst-inline-touching-normal
            types: [text]
            types_or: [python, rst]
          # Eval should never be used (can do arbitrary code execution)
          - id: python-no-eval
          # Enforce the use of type annotations instead of docstring type comments
          - id: python-use-type-annotations
