name: variete-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - rasterio
  - gdal>=3.2
  - tqdm

  - pytest
  - flake8
  - matplotlib
  - sphinx-book-theme
  - sphinx
  - numpydoc
  - myst-nb
  - sphinxcontrib-programoutput
  - sphinx-design
  - sphinx-autodoc-typehints
  - sphinx-gallery
